#pragma once
// ─────────────────────────────────────────────────────────────────────────
// GENERATED by tools/theme/generate_winui_tokens.py — DO NOT EDIT.
// Brief 34 Parte A. Todos los valores provienen de la fuente oficial de WinUI 3;
// ningún hex está escrito a mano.
//   Fuente : microsoft-ui-xaml controls/dev/CommonStyles/Common_themeresources_any.xaml @ 8463f45162149de0ec3ad7df752596893fe3e13e
//   Tokens : 83 <Color> por tema (Default=OSCURO / Light / HighContrast)
//   Fecha  : 2026-07-25
// Regenerar: python tools/theme/generate_winui_tokens.py --source <xaml>
// NOTA: HighContrast son placeholders (#FF0000) — en WinUI real HC se mapea a
//       SystemColor* del SO (brief 34 Parte F, GetSysColor). Aquí se emiten crudos.
// ─────────────────────────────────────────────────────────────────────────
#include "Math/Color.h"

namespace FluentUI {

// Tokens de color WinUI 3 (semi-transparentes: se COMPONEN sobre el fondo).
struct WinUITokens {
    Color AccentFillColorDisabled;
    Color AccentTextFillColorDisabled;
    Color CardBackgroundFillColorDefault;
    Color CardBackgroundFillColorSecondary;
    Color CardBackgroundFillColorTertiary;
    Color CardStrokeColorDefault;
    Color CardStrokeColorDefaultSolid;
    Color ControlAltFillColorDisabled;
    Color ControlAltFillColorQuarternary;
    Color ControlAltFillColorSecondary;
    Color ControlAltFillColorTertiary;
    Color ControlAltFillColorTransparent;
    Color ControlFillColorDefault;
    Color ControlFillColorDisabled;
    Color ControlFillColorInputActive;
    Color ControlFillColorQuarternary;
    Color ControlFillColorSecondary;
    Color ControlFillColorTertiary;
    Color ControlFillColorTransparent;
    Color ControlOnImageFillColorDefault;
    Color ControlOnImageFillColorDisabled;
    Color ControlOnImageFillColorSecondary;
    Color ControlOnImageFillColorTertiary;
    Color ControlSolidFillColorDefault;
    Color ControlStrokeColorDefault;
    Color ControlStrokeColorForStrongFillWhenOnImage;
    Color ControlStrokeColorOnAccentDefault;
    Color ControlStrokeColorOnAccentDisabled;
    Color ControlStrokeColorOnAccentSecondary;
    Color ControlStrokeColorOnAccentTertiary;
    Color ControlStrokeColorSecondary;
    Color ControlStrongFillColorDefault;
    Color ControlStrongFillColorDisabled;
    Color ControlStrongStrokeColorDefault;
    Color ControlStrongStrokeColorDisabled;
    Color DividerStrokeColorDefault;
    Color FocusStrokeColorInner;
    Color FocusStrokeColorOuter;
    Color LayerFillColorAlt;
    Color LayerFillColorDefault;
    Color LayerOnAccentAcrylicFillColorDefault;
    Color LayerOnAcrylicFillColorDefault;
    Color LayerOnMicaBaseAltFillColorDefault;
    Color LayerOnMicaBaseAltFillColorSecondary;
    Color LayerOnMicaBaseAltFillColorTertiary;
    Color LayerOnMicaBaseAltFillColorTransparent;
    Color SmokeFillColorDefault;
    Color SolidBackgroundFillColorBase;
    Color SolidBackgroundFillColorBaseAlt;
    Color SolidBackgroundFillColorQuarternary;
    Color SolidBackgroundFillColorQuinary;
    Color SolidBackgroundFillColorSecondary;
    Color SolidBackgroundFillColorSenary;
    Color SolidBackgroundFillColorTertiary;
    Color SolidBackgroundFillColorTransparent;
    Color SubtleFillColorDisabled;
    Color SubtleFillColorSecondary;
    Color SubtleFillColorTertiary;
    Color SubtleFillColorTransparent;
    Color SurfaceStrokeColorDefault;
    Color SurfaceStrokeColorFlyout;
    Color SurfaceStrokeColorInverse;
    Color SystemFillColorAttentionBackground;
    Color SystemFillColorCaution;
    Color SystemFillColorCautionBackground;
    Color SystemFillColorCritical;
    Color SystemFillColorCriticalBackground;
    Color SystemFillColorNeutral;
    Color SystemFillColorNeutralBackground;
    Color SystemFillColorSolidAttentionBackground;
    Color SystemFillColorSolidNeutral;
    Color SystemFillColorSolidNeutralBackground;
    Color SystemFillColorSuccess;
    Color SystemFillColorSuccessBackground;
    Color TextFillColorDisabled;
    Color TextFillColorInverse;
    Color TextFillColorPrimary;
    Color TextFillColorSecondary;
    Color TextFillColorTertiary;
    Color TextOnAccentFillColorDisabled;
    Color TextOnAccentFillColorPrimary;
    Color TextOnAccentFillColorSecondary;
    Color TextOnAccentFillColorSelectedText;

    static constexpr WinUITokens Dark();            // ThemeDictionary "Default"
    static constexpr WinUITokens Light();           // ThemeDictionary "Light"
    static constexpr WinUITokens HighContrastRaw(); // ThemeDictionary "HighContrast" (placeholders)
};

constexpr WinUITokens WinUITokens::Dark() {
    return WinUITokens{
        .AccentFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.156863f), // #28FFFFFF
        .AccentTextFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.364706f), // #5DFFFFFF
        .CardBackgroundFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.05098f), // #0DFFFFFF
        .CardBackgroundFillColorSecondary = Color(1.0f, 1.0f, 1.0f, 0.031373f), // #08FFFFFF
        .CardBackgroundFillColorTertiary = Color(1.0f, 1.0f, 1.0f, 0.070588f), // #12FFFFFF
        .CardStrokeColorDefault = Color(0.0f, 0.0f, 0.0f, 0.098039f), // #19000000
        .CardStrokeColorDefaultSolid = Color(0.109804f, 0.109804f, 0.109804f, 1.0f), // #1C1C1C
        .ControlAltFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .ControlAltFillColorQuarternary = Color(1.0f, 1.0f, 1.0f, 0.070588f), // #12FFFFFF
        .ControlAltFillColorSecondary = Color(0.0f, 0.0f, 0.0f, 0.098039f), // #19000000
        .ControlAltFillColorTertiary = Color(1.0f, 1.0f, 1.0f, 0.043137f), // #0BFFFFFF
        .ControlAltFillColorTransparent = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .ControlFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.058824f), // #0FFFFFFF
        .ControlFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.043137f), // #0BFFFFFF
        .ControlFillColorInputActive = Color(0.117647f, 0.117647f, 0.117647f, 0.701961f), // #B31E1E1E
        .ControlFillColorQuarternary = Color(1.0f, 1.0f, 1.0f, 0.058824f), // #0FFFFFFF
        .ControlFillColorSecondary = Color(1.0f, 1.0f, 1.0f, 0.082353f), // #15FFFFFF
        .ControlFillColorTertiary = Color(1.0f, 1.0f, 1.0f, 0.031373f), // #08FFFFFF
        .ControlFillColorTransparent = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .ControlOnImageFillColorDefault = Color(0.109804f, 0.109804f, 0.109804f, 0.701961f), // #B31C1C1C
        .ControlOnImageFillColorDisabled = Color(0.117647f, 0.117647f, 0.117647f, 1.0f), // #1E1E1E
        .ControlOnImageFillColorSecondary = Color(0.101961f, 0.101961f, 0.101961f, 1.0f), // #1A1A1A
        .ControlOnImageFillColorTertiary = Color(0.07451f, 0.07451f, 0.07451f, 1.0f), // #131313
        .ControlSolidFillColorDefault = Color(0.270588f, 0.270588f, 0.270588f, 1.0f), // #454545
        .ControlStrokeColorDefault = Color(1.0f, 1.0f, 1.0f, 0.070588f), // #12FFFFFF
        .ControlStrokeColorForStrongFillWhenOnImage = Color(0.0f, 0.0f, 0.0f, 0.419608f), // #6B000000
        .ControlStrokeColorOnAccentDefault = Color(1.0f, 1.0f, 1.0f, 0.078431f), // #14FFFFFF
        .ControlStrokeColorOnAccentDisabled = Color(0.0f, 0.0f, 0.0f, 0.2f), // #33000000
        .ControlStrokeColorOnAccentSecondary = Color(0.0f, 0.0f, 0.0f, 0.137255f), // #23000000
        .ControlStrokeColorOnAccentTertiary = Color(0.0f, 0.0f, 0.0f, 0.215686f), // #37000000
        .ControlStrokeColorSecondary = Color(1.0f, 1.0f, 1.0f, 0.094118f), // #18FFFFFF
        .ControlStrongFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.545098f), // #8BFFFFFF
        .ControlStrongFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.247059f), // #3FFFFFFF
        .ControlStrongStrokeColorDefault = Color(1.0f, 1.0f, 1.0f, 0.545098f), // #8BFFFFFF
        .ControlStrongStrokeColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.156863f), // #28FFFFFF
        .DividerStrokeColorDefault = Color(1.0f, 1.0f, 1.0f, 0.082353f), // #15FFFFFF
        .FocusStrokeColorInner = Color(0.0f, 0.0f, 0.0f, 0.701961f), // #B3000000
        .FocusStrokeColorOuter = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .LayerFillColorAlt = Color(1.0f, 1.0f, 1.0f, 0.05098f), // #0DFFFFFF
        .LayerFillColorDefault = Color(0.227451f, 0.227451f, 0.227451f, 0.298039f), // #4C3A3A3A
        .LayerOnAccentAcrylicFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.035294f), // #09FFFFFF
        .LayerOnAcrylicFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.035294f), // #09FFFFFF
        .LayerOnMicaBaseAltFillColorDefault = Color(0.227451f, 0.227451f, 0.227451f, 0.45098f), // #733A3A3A
        .LayerOnMicaBaseAltFillColorSecondary = Color(1.0f, 1.0f, 1.0f, 0.058824f), // #0FFFFFFF
        .LayerOnMicaBaseAltFillColorTertiary = Color(0.172549f, 0.172549f, 0.172549f, 1.0f), // #2C2C2C
        .LayerOnMicaBaseAltFillColorTransparent = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .SmokeFillColorDefault = Color(0.0f, 0.0f, 0.0f, 0.301961f), // #4D000000
        .SolidBackgroundFillColorBase = Color(0.12549f, 0.12549f, 0.12549f, 1.0f), // #202020
        .SolidBackgroundFillColorBaseAlt = Color(0.039216f, 0.039216f, 0.039216f, 1.0f), // #0A0A0A
        .SolidBackgroundFillColorQuarternary = Color(0.172549f, 0.172549f, 0.172549f, 1.0f), // #2C2C2C
        .SolidBackgroundFillColorQuinary = Color(0.2f, 0.2f, 0.2f, 1.0f), // #333333
        .SolidBackgroundFillColorSecondary = Color(0.109804f, 0.109804f, 0.109804f, 1.0f), // #1C1C1C
        .SolidBackgroundFillColorSenary = Color(0.215686f, 0.215686f, 0.215686f, 1.0f), // #373737
        .SolidBackgroundFillColorTertiary = Color(0.156863f, 0.156863f, 0.156863f, 1.0f), // #282828
        .SolidBackgroundFillColorTransparent = Color(0.12549f, 0.12549f, 0.12549f, 0.0f), // #00202020
        .SubtleFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .SubtleFillColorSecondary = Color(1.0f, 1.0f, 1.0f, 0.058824f), // #0FFFFFFF
        .SubtleFillColorTertiary = Color(1.0f, 1.0f, 1.0f, 0.039216f), // #0AFFFFFF
        .SubtleFillColorTransparent = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .SurfaceStrokeColorDefault = Color(0.458824f, 0.458824f, 0.458824f, 0.4f), // #66757575
        .SurfaceStrokeColorFlyout = Color(0.0f, 0.0f, 0.0f, 0.2f), // #33000000
        .SurfaceStrokeColorInverse = Color(0.0f, 0.0f, 0.0f, 0.058824f), // #0F000000
        .SystemFillColorAttentionBackground = Color(1.0f, 1.0f, 1.0f, 0.031373f), // #08FFFFFF
        .SystemFillColorCaution = Color(0.988235f, 0.882353f, 0.0f, 1.0f), // #FCE100
        .SystemFillColorCautionBackground = Color(0.262745f, 0.207843f, 0.098039f, 1.0f), // #433519
        .SystemFillColorCritical = Color(1.0f, 0.6f, 0.643137f, 1.0f), // #FF99A4
        .SystemFillColorCriticalBackground = Color(0.266667f, 0.152941f, 0.14902f, 1.0f), // #442726
        .SystemFillColorNeutral = Color(1.0f, 1.0f, 1.0f, 0.545098f), // #8BFFFFFF
        .SystemFillColorNeutralBackground = Color(1.0f, 1.0f, 1.0f, 0.031373f), // #08FFFFFF
        .SystemFillColorSolidAttentionBackground = Color(0.180392f, 0.180392f, 0.180392f, 1.0f), // #2E2E2E
        .SystemFillColorSolidNeutral = Color(0.615686f, 0.615686f, 0.615686f, 1.0f), // #9D9D9D
        .SystemFillColorSolidNeutralBackground = Color(0.180392f, 0.180392f, 0.180392f, 1.0f), // #2E2E2E
        .SystemFillColorSuccess = Color(0.423529f, 0.796078f, 0.372549f, 1.0f), // #6CCB5F
        .SystemFillColorSuccessBackground = Color(0.223529f, 0.239216f, 0.105882f, 1.0f), // #393D1B
        .TextFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.364706f), // #5DFFFFFF
        .TextFillColorInverse = Color(0.0f, 0.0f, 0.0f, 0.894118f), // #E4000000
        .TextFillColorPrimary = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .TextFillColorSecondary = Color(1.0f, 1.0f, 1.0f, 0.772549f), // #C5FFFFFF
        .TextFillColorTertiary = Color(1.0f, 1.0f, 1.0f, 0.529412f), // #87FFFFFF
        .TextOnAccentFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.529412f), // #87FFFFFF
        .TextOnAccentFillColorPrimary = Color(0.0f, 0.0f, 0.0f, 1.0f), // #000000
        .TextOnAccentFillColorSecondary = Color(0.0f, 0.0f, 0.0f, 0.501961f), // #80000000
        .TextOnAccentFillColorSelectedText = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
    };
}

constexpr WinUITokens WinUITokens::Light() {
    return WinUITokens{
        .AccentFillColorDisabled = Color(0.0f, 0.0f, 0.0f, 0.215686f), // #37000000
        .AccentTextFillColorDisabled = Color(0.0f, 0.0f, 0.0f, 0.360784f), // #5C000000
        .CardBackgroundFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.701961f), // #B3FFFFFF
        .CardBackgroundFillColorSecondary = Color(0.964706f, 0.964706f, 0.964706f, 0.501961f), // #80F6F6F6
        .CardBackgroundFillColorTertiary = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .CardStrokeColorDefault = Color(0.0f, 0.0f, 0.0f, 0.058824f), // #0F000000
        .CardStrokeColorDefaultSolid = Color(0.921569f, 0.921569f, 0.921569f, 1.0f), // #EBEBEB
        .ControlAltFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .ControlAltFillColorQuarternary = Color(0.0f, 0.0f, 0.0f, 0.094118f), // #18000000
        .ControlAltFillColorSecondary = Color(0.0f, 0.0f, 0.0f, 0.023529f), // #06000000
        .ControlAltFillColorTertiary = Color(0.0f, 0.0f, 0.0f, 0.058824f), // #0F000000
        .ControlAltFillColorTransparent = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .ControlFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.701961f), // #B3FFFFFF
        .ControlFillColorDisabled = Color(0.976471f, 0.976471f, 0.976471f, 0.301961f), // #4DF9F9F9
        .ControlFillColorInputActive = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .ControlFillColorQuarternary = Color(0.952941f, 0.952941f, 0.952941f, 0.760784f), // #C2F3F3F3
        .ControlFillColorSecondary = Color(0.976471f, 0.976471f, 0.976471f, 0.501961f), // #80F9F9F9
        .ControlFillColorTertiary = Color(0.976471f, 0.976471f, 0.976471f, 0.301961f), // #4DF9F9F9
        .ControlFillColorTransparent = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .ControlOnImageFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.788235f), // #C9FFFFFF
        .ControlOnImageFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .ControlOnImageFillColorSecondary = Color(0.952941f, 0.952941f, 0.952941f, 1.0f), // #F3F3F3
        .ControlOnImageFillColorTertiary = Color(0.921569f, 0.921569f, 0.921569f, 1.0f), // #EBEBEB
        .ControlSolidFillColorDefault = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .ControlStrokeColorDefault = Color(0.0f, 0.0f, 0.0f, 0.058824f), // #0F000000
        .ControlStrokeColorForStrongFillWhenOnImage = Color(1.0f, 1.0f, 1.0f, 0.34902f), // #59FFFFFF
        .ControlStrokeColorOnAccentDefault = Color(1.0f, 1.0f, 1.0f, 0.078431f), // #14FFFFFF
        .ControlStrokeColorOnAccentDisabled = Color(0.0f, 0.0f, 0.0f, 0.058824f), // #0F000000
        .ControlStrokeColorOnAccentSecondary = Color(0.0f, 0.0f, 0.0f, 0.4f), // #66000000
        .ControlStrokeColorOnAccentTertiary = Color(0.0f, 0.0f, 0.0f, 0.215686f), // #37000000
        .ControlStrokeColorSecondary = Color(0.0f, 0.0f, 0.0f, 0.160784f), // #29000000
        .ControlStrongFillColorDefault = Color(0.0f, 0.0f, 0.0f, 0.447059f), // #72000000
        .ControlStrongFillColorDisabled = Color(0.0f, 0.0f, 0.0f, 0.317647f), // #51000000
        .ControlStrongStrokeColorDefault = Color(0.0f, 0.0f, 0.0f, 0.447059f), // #72000000
        .ControlStrongStrokeColorDisabled = Color(0.0f, 0.0f, 0.0f, 0.215686f), // #37000000
        .DividerStrokeColorDefault = Color(0.0f, 0.0f, 0.0f, 0.058824f), // #0F000000
        .FocusStrokeColorInner = Color(1.0f, 1.0f, 1.0f, 0.701961f), // #B3FFFFFF
        .FocusStrokeColorOuter = Color(0.0f, 0.0f, 0.0f, 0.894118f), // #E4000000
        .LayerFillColorAlt = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .LayerFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.501961f), // #80FFFFFF
        .LayerOnAccentAcrylicFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.25098f), // #40FFFFFF
        .LayerOnAcrylicFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.25098f), // #40FFFFFF
        .LayerOnMicaBaseAltFillColorDefault = Color(1.0f, 1.0f, 1.0f, 0.701961f), // #B3FFFFFF
        .LayerOnMicaBaseAltFillColorSecondary = Color(0.0f, 0.0f, 0.0f, 0.039216f), // #0A000000
        .LayerOnMicaBaseAltFillColorTertiary = Color(0.976471f, 0.976471f, 0.976471f, 1.0f), // #F9F9F9
        .LayerOnMicaBaseAltFillColorTransparent = Color(0.0f, 0.0f, 0.0f, 0.0f), // #00000000
        .SmokeFillColorDefault = Color(0.0f, 0.0f, 0.0f, 0.301961f), // #4D000000
        .SolidBackgroundFillColorBase = Color(0.952941f, 0.952941f, 0.952941f, 1.0f), // #F3F3F3
        .SolidBackgroundFillColorBaseAlt = Color(0.854902f, 0.854902f, 0.854902f, 1.0f), // #DADADA
        .SolidBackgroundFillColorQuarternary = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .SolidBackgroundFillColorQuinary = Color(0.992157f, 0.992157f, 0.992157f, 1.0f), // #FDFDFD
        .SolidBackgroundFillColorSecondary = Color(0.933333f, 0.933333f, 0.933333f, 1.0f), // #EEEEEE
        .SolidBackgroundFillColorSenary = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .SolidBackgroundFillColorTertiary = Color(0.976471f, 0.976471f, 0.976471f, 1.0f), // #F9F9F9
        .SolidBackgroundFillColorTransparent = Color(0.952941f, 0.952941f, 0.952941f, 0.0f), // #00F3F3F3
        .SubtleFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .SubtleFillColorSecondary = Color(0.0f, 0.0f, 0.0f, 0.035294f), // #09000000
        .SubtleFillColorTertiary = Color(0.0f, 0.0f, 0.0f, 0.023529f), // #06000000
        .SubtleFillColorTransparent = Color(1.0f, 1.0f, 1.0f, 0.0f), // #00FFFFFF
        .SurfaceStrokeColorDefault = Color(0.458824f, 0.458824f, 0.458824f, 0.4f), // #66757575
        .SurfaceStrokeColorFlyout = Color(0.0f, 0.0f, 0.0f, 0.058824f), // #0F000000
        .SurfaceStrokeColorInverse = Color(1.0f, 1.0f, 1.0f, 0.082353f), // #15FFFFFF
        .SystemFillColorAttentionBackground = Color(0.964706f, 0.964706f, 0.964706f, 0.501961f), // #80F6F6F6
        .SystemFillColorCaution = Color(0.615686f, 0.364706f, 0.0f, 1.0f), // #9D5D00
        .SystemFillColorCautionBackground = Color(1.0f, 0.956863f, 0.807843f, 1.0f), // #FFF4CE
        .SystemFillColorCritical = Color(0.768627f, 0.168627f, 0.109804f, 1.0f), // #C42B1C
        .SystemFillColorCriticalBackground = Color(0.992157f, 0.905882f, 0.913725f, 1.0f), // #FDE7E9
        .SystemFillColorNeutral = Color(0.0f, 0.0f, 0.0f, 0.447059f), // #72000000
        .SystemFillColorNeutralBackground = Color(0.0f, 0.0f, 0.0f, 0.023529f), // #06000000
        .SystemFillColorSolidAttentionBackground = Color(0.968627f, 0.968627f, 0.968627f, 1.0f), // #F7F7F7
        .SystemFillColorSolidNeutral = Color(0.541176f, 0.541176f, 0.541176f, 1.0f), // #8A8A8A
        .SystemFillColorSolidNeutralBackground = Color(0.952941f, 0.952941f, 0.952941f, 1.0f), // #F3F3F3
        .SystemFillColorSuccess = Color(0.058824f, 0.482353f, 0.058824f, 1.0f), // #0F7B0F
        .SystemFillColorSuccessBackground = Color(0.87451f, 0.964706f, 0.866667f, 1.0f), // #DFF6DD
        .TextFillColorDisabled = Color(0.0f, 0.0f, 0.0f, 0.360784f), // #5C000000
        .TextFillColorInverse = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .TextFillColorPrimary = Color(0.0f, 0.0f, 0.0f, 0.894118f), // #E4000000
        .TextFillColorSecondary = Color(0.0f, 0.0f, 0.0f, 0.619608f), // #9E000000
        .TextFillColorTertiary = Color(0.0f, 0.0f, 0.0f, 0.447059f), // #72000000
        .TextOnAccentFillColorDisabled = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .TextOnAccentFillColorPrimary = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
        .TextOnAccentFillColorSecondary = Color(1.0f, 1.0f, 1.0f, 0.701961f), // #B3FFFFFF
        .TextOnAccentFillColorSelectedText = Color(1.0f, 1.0f, 1.0f, 1.0f), // #FFFFFF
    };
}

constexpr WinUITokens WinUITokens::HighContrastRaw() {
    return WinUITokens{
        .AccentFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .AccentTextFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .CardBackgroundFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .CardBackgroundFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .CardBackgroundFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .CardStrokeColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .CardStrokeColorDefaultSolid = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlAltFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlAltFillColorQuarternary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlAltFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlAltFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlAltFillColorTransparent = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlFillColorInputActive = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlFillColorQuarternary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlFillColorTransparent = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlOnImageFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlOnImageFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlOnImageFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlOnImageFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlSolidFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrokeColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrokeColorForStrongFillWhenOnImage = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrokeColorOnAccentDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrokeColorOnAccentDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrokeColorOnAccentSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrokeColorOnAccentTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrokeColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrongFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrongFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrongStrokeColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .ControlStrongStrokeColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .DividerStrokeColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .FocusStrokeColorInner = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .FocusStrokeColorOuter = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerFillColorAlt = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerOnAccentAcrylicFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerOnAcrylicFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerOnMicaBaseAltFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerOnMicaBaseAltFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerOnMicaBaseAltFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .LayerOnMicaBaseAltFillColorTransparent = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SmokeFillColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorBase = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorBaseAlt = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorQuarternary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorQuinary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorSenary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SolidBackgroundFillColorTransparent = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SubtleFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SubtleFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SubtleFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SubtleFillColorTransparent = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SurfaceStrokeColorDefault = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SurfaceStrokeColorFlyout = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SurfaceStrokeColorInverse = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorAttentionBackground = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorCaution = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorCautionBackground = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorCritical = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorCriticalBackground = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorNeutral = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorNeutralBackground = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorSolidAttentionBackground = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorSolidNeutral = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorSolidNeutralBackground = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorSuccess = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .SystemFillColorSuccessBackground = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextFillColorInverse = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextFillColorPrimary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextFillColorTertiary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextOnAccentFillColorDisabled = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextOnAccentFillColorPrimary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextOnAccentFillColorSecondary = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
        .TextOnAccentFillColorSelectedText = Color(1.0f, 0.0f, 0.0f, 1.0f), // #FF0000
    };
}

} // namespace FluentUI
